name: 🚀 Feature Request
description: RFC and ideas for new features and improvements
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the new feature
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: |
        A simple example of the new feature in action (include PHP code, YAML config, etc.)
        If the new feature changes an existing feature, include a simple before/after comparison.
